name: tensormouse
channels:
- conda-forge
- defaults
dependencies:
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py36_0
- icu=58.1=vc14_1
- jpeg=9b=vc14_1
- libpng=1.6.28=vc14_1
- libtiff=4.0.7=vc14_0
- libwebp=0.5.2=vc14_7
- opencv=3.3.0=py36_200
- openssl=1.0.2l=vc14_0
- pip=9.0.1=py36_0
- python=3.6.2=0
- qt=5.6.2=vc14_1
- setuptools=36.3.0=py36_0
- vc=14=0
- vs2015_runtime=14.0.25420=0
- wheel=0.30.0=py_1
- wincertstore=0.2=py36_0
- zlib=1.2.8=vc14_3
- mkl=2017.0.3=0
- numpy=1.13.1=py36_0
- pip:
  - bleach==1.5.0
  - html5lib==0.9999999
  - markdown==2.6.9
  - protobuf==3.4.0
  - pynput==1.3.7
  - six==1.11.0
  - tensorflow==1.3.0
  - tensorflow-tensorboard==0.1.7
  - werkzeug==0.12.2
prefix: C:\Users\psacaMan\Miniconda3\envs\tensormouse

